// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: rolemanagerpb/v1/rolemanager.proto

/*
Package rolemanagerpbv1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package rolemanagerpbv1

import (
	"context"
	"io"
	"net/http"

	extRolemanagerpbv1 "github.com/KimSeogyu/grpc-gnostic-openapi-v3-example/internal/proto/rolemanagerpb/v1"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_V1RoleManagerService_CreateRole_0(ctx context.Context, marshaler runtime.Marshaler, client extRolemanagerpbv1.V1RoleManagerServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq extRolemanagerpbv1.CreateRoleRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateRole(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_V1RoleManagerService_CreateRole_0(ctx context.Context, marshaler runtime.Marshaler, server extRolemanagerpbv1.V1RoleManagerServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq extRolemanagerpbv1.CreateRoleRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateRole(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterV1RoleManagerServiceHandlerServer registers the http handlers for service V1RoleManagerService to "mux".
// UnaryRPC     :call V1RoleManagerServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterV1RoleManagerServiceHandlerFromEndpoint instead.
func RegisterV1RoleManagerServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server extRolemanagerpbv1.V1RoleManagerServiceServer) error {

	mux.Handle("POST", pattern_V1RoleManagerService_CreateRole_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/rolemanagerpb.v1.V1RoleManagerService/CreateRole", runtime.WithHTTPPathPattern("/role"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_V1RoleManagerService_CreateRole_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_V1RoleManagerService_CreateRole_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterV1RoleManagerServiceHandlerFromEndpoint is same as RegisterV1RoleManagerServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterV1RoleManagerServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterV1RoleManagerServiceHandler(ctx, mux, conn)
}

// RegisterV1RoleManagerServiceHandler registers the http handlers for service V1RoleManagerService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterV1RoleManagerServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterV1RoleManagerServiceHandlerClient(ctx, mux, extRolemanagerpbv1.NewV1RoleManagerServiceClient(conn))
}

// RegisterV1RoleManagerServiceHandlerClient registers the http handlers for service V1RoleManagerService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "extRolemanagerpbv1.V1RoleManagerServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "extRolemanagerpbv1.V1RoleManagerServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "extRolemanagerpbv1.V1RoleManagerServiceClient" to call the correct interceptors.
func RegisterV1RoleManagerServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client extRolemanagerpbv1.V1RoleManagerServiceClient) error {

	mux.Handle("POST", pattern_V1RoleManagerService_CreateRole_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/rolemanagerpb.v1.V1RoleManagerService/CreateRole", runtime.WithHTTPPathPattern("/role"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_V1RoleManagerService_CreateRole_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_V1RoleManagerService_CreateRole_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_V1RoleManagerService_CreateRole_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"role"}, ""))
)

var (
	forward_V1RoleManagerService_CreateRole_0 = runtime.ForwardResponseMessage
)
