// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: rolemanagerpb/v1/rolemanager.proto

package rolemanagerpbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	V1RoleManagerService_CreateRole_FullMethodName = "/rolemanagerpb.v1.V1RoleManagerService/CreateRole"
)

// V1RoleManagerServiceClient is the client API for V1RoleManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type V1RoleManagerServiceClient interface {
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
}

type v1RoleManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewV1RoleManagerServiceClient(cc grpc.ClientConnInterface) V1RoleManagerServiceClient {
	return &v1RoleManagerServiceClient{cc}
}

func (c *v1RoleManagerServiceClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	out := new(CreateRoleResponse)
	err := c.cc.Invoke(ctx, V1RoleManagerService_CreateRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// V1RoleManagerServiceServer is the server API for V1RoleManagerService service.
// All implementations must embed UnimplementedV1RoleManagerServiceServer
// for forward compatibility
type V1RoleManagerServiceServer interface {
	CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error)
	mustEmbedUnimplementedV1RoleManagerServiceServer()
}

// UnimplementedV1RoleManagerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedV1RoleManagerServiceServer struct {
}

func (UnimplementedV1RoleManagerServiceServer) CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedV1RoleManagerServiceServer) mustEmbedUnimplementedV1RoleManagerServiceServer() {}

// UnsafeV1RoleManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to V1RoleManagerServiceServer will
// result in compilation errors.
type UnsafeV1RoleManagerServiceServer interface {
	mustEmbedUnimplementedV1RoleManagerServiceServer()
}

func RegisterV1RoleManagerServiceServer(s grpc.ServiceRegistrar, srv V1RoleManagerServiceServer) {
	s.RegisterService(&V1RoleManagerService_ServiceDesc, srv)
}

func _V1RoleManagerService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1RoleManagerServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V1RoleManagerService_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1RoleManagerServiceServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// V1RoleManagerService_ServiceDesc is the grpc.ServiceDesc for V1RoleManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var V1RoleManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rolemanagerpb.v1.V1RoleManagerService",
	HandlerType: (*V1RoleManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _V1RoleManagerService_CreateRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rolemanagerpb/v1/rolemanager.proto",
}
